# Generated by Django 4.2.7 on 2026-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transientpayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transientpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
