# Generated by Django 4.2.7 on 2026-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payments_date_alter_transientpayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transientpayment',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
