# Generated by Django 4.2.7 on 2026-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
