# Generated by Django 4.2.7 on 2026-04-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantdocument_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
