# Generated by Django 4.2.7 on 2026-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_feedback_reply_feedback_reply_date_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
