# Generated by Django 4.2.7 on 2026-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
