# Generated by Django 4.2.7 on 2026-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_inquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
