# Generated by Django 4.2.7 on 2026-04-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_complaint_updated_at_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=10),
        ),
    ]
