# Generated by Django 4.2.7 on 2026-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0002_boardinghouseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
