# Generated by Django 4.2.7 on 2026-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0003_boardinghouse_is_viewed_room_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
    ]
