# Generated by Django 4.2.7 on 2026-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0004_boardinghouse_has_internet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='has_internet',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
